# Nginx app values file - DEVELOPMENT ENV
common:
  environment: dev
  registryName: task-container-registry.cr.de-fra.ionos.com
  imagePullSecretName: ionos-registry-secret
  ingressClass: nginx

# ingress:
ingress:
  annotations:
      kubernetes.io/ingress.class: nginx
      kubernetes.io/ssl-redirect: "true"
      nginx.ingress.kubernetes.io/proxy-body-size: "4096m"
      nginx.ingress.kubernetes.io/proxy-buffer-size: "256k"
      nginx.ingress.kubernetes.io/proxy_buffers: "4 256k"
      nginx.ingress.kubernetes.io/proxy_busy_buffers_size: "256k"
      nginx.ingress.kubernetes.io/large-client-header-buffers: "4 100k"
      nginx.ingress.kubernetes.io/http2-max-header-size: "96k"
      meta.helm.sh/release-name: nginx

# nginx app values:
name: "nginx-app-dev"
namespace: nginx 
DNS: nginx.task.de
replicaCount: 2
imageName: nginx-prometheus
imageTag: 1.0.0
serviceType: LoadBalancer
port: 8091
targetPort: 8091
preferenceWeight: 100
resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 100m
    memory: 256Mi

