apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJ0YXNrLWNvbnRhaW5lci1yZWdpc3RyeS5jci5kZS1mcmEuaW9ub3MuY29tIjp7InVzZXJuYW1lIjoidGFzay10b2tlbiIsInBhc3N3b3JkIjoiZjkyMjliOTg3OTQ4NzZlZDFkMjJhNTlkZGU3ZjliOGIiLCJlbWFpbCI6Im1vdGltYW5hc3BAZ21haWwuY29tIiwiYXV0aCI6ImRHRnpheTEwYjJ0bGJqcG1PVEl5T1dJNU9EYzVORGczTm1Wa01XUXlNbUUxT1dSa1pUZG1PV0k0WWc9PSJ9fX0=
kind: Secret
metadata:
  name: {{ .Values.common.imagePullSecretName }}
  namespace: {{ .Values.namespace }}
  annotations:
    meta.helm.sh/release-namespace: {{ .Values.namespace }}
    meta.helm.sh/release-name: {{ .Values.namespace }}
    app.kubernetes.io/managed-by: "Helm"
type: kubernetes.io/dockerconfigjson
